apiVersion: v1
kind: Pod
metadata:
  name: counter-pod-redis
  labels:
    app: counter-pod-redis
spec:
  containers:
    - name: app
      image: ghcr.io/subicura/counter:latest
      env:
        - name: REDIS_HOST
          value: "localhost"
    - name: db
      image: redis