apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  selector:
    matchLabels:
      env: dev
      app: result
  template:
    metadata:
      labels: 
        env: dev
        app: result
    spec:
      containers:
        - name: result
          image: ghcr.io/subicura/voting/result:latest
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: postgres-svc
            - name: POSTGRES_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: result-svc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31001
      protocol: TCP
  selector:
    env: dev
    app: result