apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: vote
  template:
    metadata:
      labels:
        env: dev
        app: vote
    spec:
      containers:
        - name: vote
          image: ghcr.io/subicura/voting/vote:latest
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis-svc
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: vote-svc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31000
      protocol: TCP
  selector:
    env: dev
    app: vote