apiVersion: v1
kind: Pod
metadata:
  name: host-log
spec:
  containers:
    - name: log
      image: busybox
      args: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - mountPath: /host/var/log
          name: varlog
  volumes:
    - name: varlog
      hostPath:
        path: /var/log