apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: web
      type: deploy
  template:
    metadata:
      labels:
        env: dev
        app: web
        type: deploy
    spec:
      containers:
        - name: wordpress-deployment
          image: wordpress:5.9.1-php8.1-apache
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-deploy-svc
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              value: password
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-deploy-svc
spec:
  type: LoadBalancer
  ports:
    - port: 30000
      targetPort: 80
      protocol: TCP
  selector:
    env: dev
    app: web
    type: deploy