apiVersion: v1
kind: Pod
metadata:
  name: alpine-env
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sleep"]
      args: ["100000"]
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username.txt
              name: db-user-pass
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: db-user-pass