apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sleep"]
      args: ["100000"]
      volumeMounts:
        - mountPath: /etc/config
          name: config-vol
  volumes:
    - name: config-vol
      configMap:
        name: my-config